# Configure server
---
- name: Configure sysctl | Set statement specifying the default number of listening sockets
  become: true
  become_user: root
  sysctl:
    name: net.core.somaxconn
    value: "{{ somaxconn }}"
    sysctl_set: yes
    state: present

- name: Configure sysctl | Set how many seconds to wait for a final FIN packet before the socket is forcibly closed
  become: true
  become_user: root
  sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: "{{ fin_timeout }}"
    sysctl_set: yes
    state: present

- name: Configure sysctl | Set interval between subsequential keepalive probes
  become: true
  become_user: root
  sysctl:
    name: net.ipv4.tcp_keepalive_intvl
    value: "{{ keepalive_intvl }}"
    sysctl_set: yes
    state: present

- name: Configure sysctl | Set TCP Keepalive Settings
  become: true
  become_user: root
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: "{{ keepalive_time }}"
    sysctl_set: yes
    state: present

- name: Configure sysctl | Set maximal number of remembered connection requests
  become: true
  become_user: root
  sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: "{{ max_syn_backlog }}"
    sysctl_set: yes
    state: present

- name: Configure sysctl | Set maximal number of remembered connection requests
  become: true
  become_user: root
  sysctl:
    name: net.ipv4.tcp_keepalive_probes
    value: "{{ keepalive_probes }}"
    sysctl_set: yes
    state: present

- name: Configure sysctl | Set low latency TCP settings
  become: true
  become_user: root
  sysctl:
    name: net.ipv4.tcp_low_latency
    value: "1"
    sysctl_set: yes
    state: present
    reload: yes
