# Install and configure nginx
---
- name: Nginx | Install packages
#  become: true
#  becom_user: root
  yum: name="{{ nginx }}"

- name: Nginx | Copy config
#  become: true
#  becom_user: root
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/
    owner: root
    group: root
    mode: 0644
  register: config_result

- name: Nginx | Restart service if configs were changed
#  become: true
#  becom_user: root
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
