# Install Telegraf
---
- name: Telegraf | Install packages
  yum: name="{{ telegraf }}"

- name: Telegraf | Copy config
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/
    owner: root
    group: root
    mode: 0644
  register: config_result

- name: Telegraf | Restart service if configs were changed
  systemd:
    name: telegraf
    state: restarted
    daemon_reload: yes
